UsersBundle\Entity\Usuario:
    type: entity
    table: usuario
    indexes:
      username_index:
        columns: [ username ]
    oneToMany:
        pedidos:
            targetEntity: Pedido
            mappedBy: usuario
            
        devoluciones:
            targetEntity: Devolucion
            mappedBy: usuario
            
    repositoryClass: UsersBundle\Repository\UsuarioRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: '50'
        apellidos:
            type: string
            length: '100'
        direccion:
            type: string
            length: '100'
        ciudad:
            type: string
            length: '100'
        cp:
            type: string
            length: '50'
        telefono:
            type: string
            length: '50'
        email:
            type: string
            length: '100'
        roles:
            type: string
            length: '100'
        username:
            type: string
            length: '100'
        password:
            type: string
            length: '100'
        salt:
            type: string
            length: '100'
        is_active:
            type: boolean
    lifecycleCallbacks: {  }
