<?php

namespace UsersBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Linea_pedidoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Linea_pedidoRepository extends EntityRepository
{
}
