<?php

namespace UsersBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends EntityRepository
{
	public function login($username,$password){
		return $this->getEntityManager()
            ->createQuery('SELECT u.username,u.password FROM UsersBundle:Usuario u WHERE (u.username = :username AND
             u.password = :password')->setParameters(array(
   			 ':username' => $username,
   			 ':password' => $password))->getArrayResult();
	
	}
}
